version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      - test_DBHOST=db
      - test_DBNAME=testdb
      - test_DBPASSWORD=postgres
      - test_DBUSER=postgres
      - test_DBPORT=5432
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
