package provider_test

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strconv"
	"testing"
	"time"

	"github.com/joho/godotenv"
	pactmodels "github.com/pact-foundation/pact-go/v2/models"
	"github.com/pact-foundation/pact-go/v2/provider"
	"github.com/pact-foundation/pact-go/v2/proxy"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"

	interfaces "github.com/LanternNassi/IMSController/internal/Interfaces"
	"github.com/LanternNassi/IMSController/internal/database"
	imsmodels "github.com/LanternNassi/IMSController/internal/models"
	"github.com/LanternNassi/IMSController/internal/server"
	"github.com/LanternNassi/IMSController/internal/utils"
)

// TestIMSControllerProvider verifies the IMSController API against the pact files
// generated by the consumer tests.
//
// Prerequisites:
//  1. Run the consumer tests first: go test ./internal/contract/consumer/...
//  2. Ensure the test database is reachable (test_DB* env vars in .env).
func TestIMSControllerProvider(t *testing.T) {
	_ = godotenv.Load(filepath.Join("..", "..", "..", ".env"))

	dbClient, rawDB, err := connectTestDB()
	require.NoError(t, err, "failed to connect to test database")
	require.NoError(t, dbClient.Migrate(), "failed to migrate test database")

	t.Cleanup(func() {
		rawDB.Migrator().DropTable(
			&imsmodels.Backup{},
			&imsmodels.Bill{},
			&imsmodels.Installation{},
			&imsmodels.User{},
			&imsmodels.Client{},
		)
	})

	_, echoServer := server.NewEchoServer(dbClient)
	ts := httptest.NewServer(echoServer)
	t.Cleanup(ts.Close)

	pactDir, _ := filepath.Abs(filepath.Join("..", "..", "..", "pacts"))

	verifier := provider.NewVerifier()
	err = verifier.VerifyProvider(t, provider.VerifyRequest{
		ProviderBaseURL: ts.URL,
		PactDirs:        []string{pactDir},
		Provider:        "IMSController",

		// Replace placeholder auth tokens with freshly signed JWTs so protected
		// routes accept requests during verification.
		RequestFilter: authInjector(),

		StateHandlers: buildStateHandlers(dbClient),
	})
	require.NoError(t, err)
}

// connectTestDB builds a connection using the same test_* env vars as the
// existing server test suite.
func connectTestDB() (interfaces.DataBaseClient, *gorm.DB, error) {
	port, _ := strconv.Atoi(os.Getenv("test_DBPORT"))
	dsn := fmt.Sprintf(
		"host=%s user=%s password=%s dbname=%s port=%d sslmode=disable",
		os.Getenv("test_DBHOST"),
		os.Getenv("test_DBUSER"),
		os.Getenv("test_DBPASSWORD"),
		os.Getenv("test_DBNAME"),
		port,
	)
	return database.NewDatabaseClient(dsn)
}


func authInjector() proxy.Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Header.Get("Authorization") != "" {
				token, err := utils.GenerateToken(1, "pact-test@example.com")
				if err == nil {
					r.Header.Set("Authorization", "Bearer "+token)
				}
			}
			next.ServeHTTP(w, r)
		})
	}
}

// buildStateHandlers maps the "Given" provider state strings used in consumer
// tests to setup functions that seed the test database accordingly.
func buildStateHandlers(db interfaces.DataBaseClient) pactmodels.StateHandlers {
	ctx := context.Background()

	seedClient := func(id, email string) {
		c := &imsmodels.Client{
			ClientID:     id,
			FirstName:    "John",
			LastName:     "Doe",
			Email:        email,
			Phone:        "+256700000000",
			Address:      "123 Main St",
			BusinessName: "ACME Corp",
			Status:       "connected",
			ValidTill:    time.Now().AddDate(0, 1, 0),
		}
		db.AddClient(ctx, c) //nolint:errcheck
	}

	seedUser := func() {
		hashed, _ := utils.HarshPassword("secret123")
		db.AddUser(ctx, &imsmodels.User{ //nolint:errcheck
			Username: "johndoe",
			Password: hashed,
			Email:    "john@example.com",
			Verified: true,
		})
	}

	return pactmodels.StateHandlers{

		// ─── client states ────────────────────────────────────────────────
		"clients exist": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedClient("test-client-id", "john@example.com")
			}
			return nil, nil
		},

		"a new client can be registered": func(_ bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			return nil, nil
		},

		"a client with ID test-client-id exists": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedClient("test-client-id", "john@example.com")
			}
			return nil, nil
		},

		"a client with ID abc123 exists": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedClient("abc123", "jane@example.com")
			}
			return nil, nil
		},

		// ─── user states ──────────────────────────────────────────────────
		"users exist": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedUser()
			}
			return nil, nil
		},

		"no user with email john@example.com exists": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				users, _ := db.GetUsers(ctx, &imsmodels.User{Email: "john@example.com"})
				for _, u := range users {
					db.DeleteUser(ctx, strconv.FormatUint(uint64(u.ID), 10)) //nolint:errcheck
				}
			}
			return nil, nil
		},

		"a user with email john@example.com exists": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedUser()
			}
			return nil, nil
		},

		"a user with ID 1 exists": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedUser()
			}
			return nil, nil
		},

		// ─── installation states ──────────────────────────────────────────
		"installations exist": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedClient("test-client-id", "john@example.com")
				db.AddInstallation(ctx, &imsmodels.Installation{ //nolint:errcheck
					ClientID:          "test-client-id",
					Installation_type: "server",
					Computer_name:     "DESKTOP-001",
					IMS_version:       "1.0.0",
					Operating_system:  "Windows 11",
					RAM:               "16GB",
					Processor:         "Intel Core i7",
					Active:            "true",
				})
			}
			return nil, nil
		},

		"an installation with ID 1 exists": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedClient("test-client-id", "john@example.com")
				db.AddInstallation(ctx, &imsmodels.Installation{ //nolint:errcheck
					ClientID:          "test-client-id",
					Installation_type: "server",
					Computer_name:     "DESKTOP-001",
					IMS_version:       "1.0.0",
					Operating_system:  "Windows 11",
					RAM:               "16GB",
					Processor:         "Intel Core i7",
					Active:            "true",
				})
			}
			return nil, nil
		},

		// ─── backup states ────────────────────────────────────────────────
		"backups exist": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedClient("test-client-id", "john@example.com")
				bill, _ := db.AddBill(ctx, &imsmodels.Bill{ClientID: "test-client-id"})
				db.AddBackup(ctx, &imsmodels.Backup{ //nolint:errcheck
					ClientID: "test-client-id",
					Name:     "daily-backup-2024",
					Backup:   "s3://bucket/backup.tar.gz",
					Size:     1024,
					BillID:   bill.ID,
				})
			}
			return nil, nil
		},

		"a backup with ID 1 exists": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedClient("test-client-id", "john@example.com")
				bill, _ := db.AddBill(ctx, &imsmodels.Bill{ClientID: "test-client-id"})
				db.AddBackup(ctx, &imsmodels.Backup{ //nolint:errcheck
					ClientID: "test-client-id",
					Name:     "daily-backup-2024",
					Backup:   "s3://bucket/backup.tar.gz",
					Size:     1024,
					BillID:   bill.ID,
				})
			}
			return nil, nil
		},

		// ─── bill states ──────────────────────────────────────────────────
		"bills exist": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedClient("test-client-id", "john@example.com")
				db.AddBill(ctx, &imsmodels.Bill{ClientID: "test-client-id"}) //nolint:errcheck
			}
			return nil, nil
		},

		"a bill with ID 1 exists": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedClient("test-client-id", "john@example.com")
				db.AddBill(ctx, &imsmodels.Bill{ClientID: "test-client-id"}) //nolint:errcheck
			}
			return nil, nil
		},

		"bills exist for client abc123": func(setup bool, _ pactmodels.ProviderState) (pactmodels.ProviderStateResponse, error) {
			if setup {
				seedClient("abc123", "abc123@example.com")
				db.AddBill(ctx, &imsmodels.Bill{ClientID: "abc123"}) //nolint:errcheck
			}
			return nil, nil
		},
	}
}
