name: CI Pipeline

on:
  push:
    branches:
      - Staging
  pull_request:
    branches:
      - Staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Compose
        run: docker-compose --version

      # Step 5: Run tests
      - name: Run tests
        run: make test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # Step 6: Clean up (optional)
      - name: Clean up
        run: make clean
