name: CI Pipeline

on:
  push:
    branches:
      - Staging
  pull_request:
    branches:
      - Staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      
      # Step 4: Build the Docker containers (optional, if your Makefile has a build step)
      - name: Build containers
        run: make build

      # Step 5: Run tests
      - name: Run tests
        run: make test

      # Step 6: Clean up (optional)
      - name: Clean up
        run: make clean
